# -*- coding: utf-8 -*-
"""hw1 203046.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouLLNR0yW06YEpBeIztIpC0FfGMfzKAO

# Information Security

## CMP-5006

## Homework 1

### Exercise 1

Let $n$ be a positive integer. A Latin square of order $n$ is an $n \times n$ array $L$ of the integers $1, ... , n$ such that every one of the $n$ integers occurs exactly once in each row and each column of $L$. An example of a Latin square of order 3 is as follows:

||C1|C2|C3|
|-|-|-|-|
|R1|1|2|3|
|R2|3|1|2|
|R3|2|3|1|

Given any Latin square $L$ of order $n$, we can define a related Latin Square Cryptosystem. Let the sets $P$ = $C$ = $K$ = ${1, . . . , n}$, be the sets representing the space for the plaintext, ciphertext and keys. For $1 ≤ i ≤ n$, the encryption rule $e_i$ is defined to be $e_i(j) = L(i,j).$ Here, $i$ would be the key, $j$ the plaintext, and  $e_i(j)$ the ciphertext.

Give a complete proof that this Latin Square Cryptosystem achieves perfect
secrecy provided that every key is used with equal probability.

                              Solution:

In order to proof that a criptosystem meets the necesary and sufficient conditions of perfect secrecy, we have to proof that for the Latin Square Cryptosystem:

$∀$ $x$ $∈$ $P$, $y$ $∈$ $C$:

\begin{align}
P_r[x/y] = P_r[x]             
\end{align}         
                
Now, we also know from for Bayes' theorem that for each $x$ $∈$ $P$ and $c$ $∈$ $C$:
  
   \begin{align}
        P_r (p/c) = \frac{ P_r (p)\times P_r (c/p)} {P_r(c)}
    \end{align}

Given that any one key is used equiprobably, because each number appears once in a column, if a particuluar $j$ is known there is a unique key that encrypts $j$ to $L(i,j)$ out of $n$ keys. Now for $P_r(c)$, any single $L(i,j)$ happens $n$ times in the square among the $n^2$ possible instances,

\begin{align}
P_r(p) = P_r(p/c)=\frac { P_r(p) \times \frac {1}{n}} { \frac {n}{n^2}}
\end{align}

Then, the LS Cryptosystem guarantees perfect secrecy as long as there equiprobability within the keys.

In terms of the ciphertexts:

If the cryptosystems complies with perfect secrecy, then for $p$ $∈$ $P$, $c$ $∈$ $C$

\begin{align}
P_r(p) = P_r(p/c)
\end{align}

Applying the Bayes' theorem, it is possible to infere that for any $c$ $∈$ $C$:  

\begin{align}
P_r(c)= \frac {P_r(p)\times P_r(c/p)}{P_r(p/c)}= \frac {P_r(p) \times P_r(c/p)} {P_r(p)}= P_r(c/p)
\end{align}

Given that the size of $P$, $C$ and $K$ are the same there exists unicity among the one key $n$ which encrypts for $p$ to $c$. Hence, for any $c$ $∈$ $C$:

\begin{align}
P_r(c/p)= \frac {1}{n}
\end{align}

Finally, after this finding we can conclude that any ciphertext is equally probable to occur.

### Exercise 2

Consider a cryptosystem in which the sets representing the plaintext, ciphertext and keys are: $P = { a, b, c}$, $K = {K1 , K2 , K3 }$ and $C ={1, 2, 3, 4}$. Suppose the encryption matrix is as follows:

||a| b| c|
|-|-|-|-|
|K1| 1| 2| 3|
|K2| 2| 3| 4|
|K3| 3| 4| 1|

Given that keys are chosen equiprobably, and the plaintext probability distribution is $Pr[ a] = 1/2$, $Pr[b] = 1/3$, $Pr[c] = 1/6$, compute $H(P)$, $H(C)$, $H(K)$, $H(K|C)$, and $H(P|C)$.

                                  Solution:

Taking into account the matrix given and the respective values of $P_r(a)=\frac {1}{2}$, $P_r(b)=\frac{1}{3}$, $P_r(c)=\frac{1}{6}$,we are looking for the values of $H(P)$, $H(C)$, $H(K)$, $H(K|C)$, and $H(P|C)$ where $P=a,b,c$, $K=K_1, K_2, K_3$, and $ C=1,2,3,4$.

First we should take attention to the fact that:

\begin{align}
H(K|C) = H(K) + H(P) - H(C)
\end{align}

\begin{align}
H(P|C) = H(P,C) - H (C)
\end{align}



Let's start with $H(C)$, with $ c ∈ C, k ∈ K, p ∈ P $ and implementing Shannon's expression we have:

 \begin{align}
  H(c) = - ∑ ( P_r (k)  log_2  P_r (p) )  
 \end{align}

Now for $H(C)$, the computation would be:

\begin{align}
P_r(1)=P_r(K_1) \times P_r(a) + P_r(K_2) \times 0 + P_r(K_3) \times P_r(C)=(1/3)(1/2) + (1/3)(1/6)= \frac{2}{9}
\end{align}

\begin{align}
P_r(2)= P_r(K_1)\times 0 + P_r(K_2) \times P_r(b) + P_r(K_3) \times P_r(c) = (1/3) \times (1/3) + (1/3) \times (1/6)= \frac {5}{18}   
\end{align}

\begin{align}
P_r(3) = P_r(K_1) \times P_r(a) + P_r(K_2) \times P_r(b) + P_r(K_3) \times P_r(c) = (1/3)\times (1/3) + (1/2)(1/3) \times (1/3)(1/6) = \frac {1}{3}
\end{align}

With these results then the entropy of the ciphertext could be determined as:

\begin{align}
H(C) = -\frac {2}{9} log_2 (\frac {2}{9}) -\frac {5}{18} log_2 (\frac {5}{18}) -\frac {1}{3} log_2 (\frac {1}{3})-\frac {1}{6} log_2 (\frac {1}{6}) ≈ 1.95
\end{align}


Continuing for $H(P)$, with similar process:

\begin{align}
H(P)= \frac{1}{2} log_2 (2) + \frac{1}{3} log_2 (3) + \frac{1}{6}log_2 (6)= \frac{2}{3} +\frac{1}{2}log_2(3) ≈ 1,459
\end{align}

Knowing the equiprobability of the keays, $H(K)$ is calculated by:

\begin{align}
H(K) = \frac{1}{3} log_2 (3) + \frac{1}{3} log_2 (3)+ \frac{1}{3} log_2 (3) ≈1.58
\end{align}

Using the theorem described previously we get:

\begin{align}
H(K|C) = H(K) + H(P) - H(C) ≈ 1.08
\end{align}


Now looking to solve for $H(P,C)$:

\begin{align}
P_r(a, 1) = P_r(a) P_r(1|a) = \frac{1}{2} * \frac{1}{3} = \frac{1}{6}
\end{align}

Applying the same principle we know that the non-zero probabilities are:

\begin{align}
P_r(a,i) = \frac{1}{6} ; i= 2,3
\end{align}


\begin{align}
P_r(b,i) = \frac{1}{9} ; i= 2,3,4
\end{align}


\begin{align}
P_r(c,i) = \frac{1}{18} ; i= 1,3,4
\end{align}

Thus the value of $H(P,C)$:

\begin{align}
H(P,C) = 3 \times [ \frac{1}{6} log_2 (6) + \frac {1}{9} log_2 (9) + \frac {1}{18} log_2 (18) ] ≈ 3.044
\end{align}

Finally solving for $H(P|C)$

\begin{align}
H(P|C) = H(P,C) - H(C) ≈ 1.08
\end{align}

:### Exercise 3

Compute $H(K|C)$ and $H(K|P, C)$ for the Affine Cipher, assuming that keys are used equiprobably and the plaintexts are equiprobable.

                            Solution:

The aim is to solve for $H(K|C)$ and $H(K|P,C)$ for the affine cipher.Let's start by evaluating the entropy of the key space $(K)$ in respect to the ciphertext $(C)$. Considering the fact that keys are uniformly distributed, there is a sign for equal likelihood for the usage of each key. The entropy of the key space $H(K)$ is described using the expression where $P_r(k)$ assings for probability of each key within the key space:

\begin{align}
H(K)=-∑P_r(k) * log_2 P_r(k)
\end{align}

Then, the entropy of the key space is determined by:

\begin{align}
H(K)=-∑(\frac{1}{|K|}* log_2 \frac{1}{|K|})
\end{align}


\begin{align}
H(K)=-|K|*\frac{1}{|K|}* log_2 \frac{1}{|K|}
\end{align}


\begin{align}
H(K)=|K|* (-log_2 \frac{1}{|K|})
\end{align}


\begin{align}
H(K)=|K|* log_2 (|K|)
\end{align}

Accounting that the key space distribution is uniform, the entropy of the key space given the ciphertext space $H(K|C)$ reflects the key space's entropy, which has been determined previously as $H(K)=|K|* log_2 (|K|)$

In the mission to evaluate for $H(K|P,C)$ for the Affine Cipher let's consider the entropy of the key space in regards of the probability of plaintext and ciphertext $P$ and $C$. The entropy of the key space conditioned on both the probability and ciphertext spaces (H(K|P, C)) is equivalent to the entropy of the key space conditioned on the probability space alone (H(K|P))

Given that plaintexts are uniformly distributed, each plaintext is equally probable. The entropy of the key space conditioned on the probability space (H(K|P)) can be computed as:

\begin{align}
H(K|P) = - ∑ P_r (K|P) * log_2 (P_r(K|P))
\end{align}

Where $P_r(K|P)$ detones for the likelihood of each key for a given plaintext. Now the probability of each key for a specific plaintext is also $\frac{1}{|K|}. Thus, the entropy of the key space given the probability space is:

\begin{align}
H(K|P)= - ∑ (\frac{1}{|K|}) * log_2 (\frac {1}{|K|})
\end{align}


\begin{align}
H(K|P)= - |K| * (\frac{1}{|K|}) * log_2 (\frac {1}{|K|})
\end{align}


\begin{align}
H(K|P)= |K|*-( log_2 (\frac {1}{|K|}))
\end{align}


\begin{align}
H(K|P)= |K|* log_2 (|K|)
\end{align}

Testifying that both the key space and the probability space are uniformly distributed, the entropy of the key space conditioned on both the probability and ciphertext spaces $(H(K|P, C))$ aligns with the entropy of the key space conditioned on the probability space $(H(K|P))$, which we know is $|K| * log2(|K|)$.

Concluding, the entropy of the key space conditioned on the ciphertext space $(H(K|C)) is |K| * log2(|K|)$, and similarly, the entropy of the key space conditioned on both the probability space and the ciphertext space is also $|K| * log2(|K|)$.

### Exercise 4

Show that the unicity distance of the Hill Cipher (with an $m \times m$ encryption matrix) is less than $\frac{m}{R_L}$ . (Note that the number of alphabetic characters ina plaintext of this length is $\frac{m^2}{R_L}$.)

                                Solution:

In order to show that the unicity distance of the Hill Cipher is less than $\frac{m}{RL}$ where:

$m$: Dimensions of the encryption matrix $(m\times m)$.

$R$:Indicates the number of potential characters in the plaintext alphabet.

$L$:Indicates the count of potential characters in the ciphertext alphabet.

Firstly, we need to determine the number of possibles keys for the Hill Cipher. Given an encryption matrix of size $m \times m$, each element in the matrix can take one of $R$ values. Consequently, there are R^(m^2) potential encryption keys.

Next, we determine the number of possible plaintexts of length $\frac {m^2}{RL}$.Each position in the plaintext can assume one of $R$ values, resulting in $R^(\frac{m^2}{RL})$ possible plaintexts of this length.

Now, let's define the unicity distance $(D)$ as:

\begin{align}
D= \frac{m^2}{RL} + 1
\end{align}

Our objective is to prove that:

\begin{align}
D < \frac{m}{RL}
\end{align}

To achieve this, we compare the two expressions:

\begin{align}
\frac{m^2}{RL} + 1  < \frac{m}{RL}
\end{align}

By subtracting $\frac {m}{RL}$ from both sides, we obtain:

\begin{align}
\frac{m^2}{RL} - \frac{m}{RL} + 1 < 0
\end{align}

Mixing terms with the same denominator results:

\begin{align}
\frac{m^(2) - m}{RL} +1 < 0
\end{align}

Given that $m^2 -m$ is positive $(since m>1)$, we get:

\begin{align}
\frac{(m^2 - m)}{RL +1} > \frac {1}{RL}
\end{align}

Therefore, we can conclude that:

\begin{align}
 D > \frac{1}{RL}
\end{align}

Thus, the unicity distance of the Hill Cipher is greater than

\begin{align}
\frac{1}{RL}
\end{align}

In other words, this means that the unicity distance is more than the reciprocal of the product of the number of characters in the plaintext alphabet $(R)$ and the number of characters in the ciphertext alphabet $(L)$.

References:

Y. Z. Ding and M. O. Rabin. Hyper-encryption and everlasting security. In 19th Symp.
on Theoretical Aspects of Computer Science (STACS), pp. 1-26, 2002.

• A. J. Menezes, P. C. van Oorschot, and S. A. Vanstone. Handbook of Applied Cryptography.
CRC Press Series on Discrete Mathematics and Its Applications, 1997.

• J. Rothe. Some facets of complexity theory and cryptography: A five-lecture tutorial.
ACM Computing Surveys 34(4), pp. 504–549, 2002
"""